name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            os_name: macos
          - os: ubuntu-22.04
            os_name: linux
          - os: windows-latest
            os_name: windows

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      - name: Install certifi
        run: pip install --upgrade certifi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary
        run: |
          pyinstaller --onefile PackWize/main.py -n packwize

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packwize-${{ matrix.os_name }}
          path: dist/packwize*
