name: Build Linux Binarie (glibc 2.35+)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary
        run: |
          pyinstaller --onefile PackWize/main.py -n packwize

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packwize-ubuntu-22.04
          path: dist/packwize*
